### PR TITLE
[Improvement] Fix PAT-B1001.害死人不偿命的(3n+1)猜想.java

### PR DESCRIPTION
**Pull request by Tianxingkai**
根据PAT格式要求修改代码

### CODE REVIEW

**Comment by Tianxingkai** [comment]
@JaydenHD PTAL

**Comment by JaydenHD** [comment]
@Tianxingkai 你好，你提交的“修改代码”有错误，不能正确地解决题目

**Comment by JaydenHD** [comment]
您好，感谢您的提交！代码主要由 @QuakeWang 负责。
@QuakeWang PTAL！

**Review by QuakeWang — APPROVED** [review]
/approve

**Comment by QuakeWang** [comment]
@Tianxingkai Thank you for your contribution and look forward to participating in the future ~

**Comment by QuakeWang** [comment]
@Tianxingkai Thank you for your contribution and look forward to participating in the future ~

**Comment by QuakeWang** [comment]
@Tianxingkai Thank you for your contribution and look forward to participating in the future ~

**Pull request merged**
