### PR TITLE
PAT-A1046.Shortest Distance.java renamed to PAT-A1046.ShortestDistanc…

### LINKED ISSUE #196: Fix 'The name of the outer type and the file do not match.' issue in PAT\javaSrc\PAT-A1046.Shortest Distance.java
[CodeFactor](https://www.codefactor.io/repository/github/os-edu/ko--csp) found an issue: The name of the outer type and the file do not match.

It's currently on:
[PAT\javaSrc\PAT-A1046.Shortest Distance.java:5](https://www.codefactor.io/repository/github/os-edu/ko--csp/source/main/PAT/javaSrc/PAT-A1046.Shortest%20Distance.java#L5)

### PR DESCRIPTION
**Pull request by ANURAG-PATHAK**
fix #196

### CODE REVIEW

**Comment by QuakeWang** [comment]
hi, is this one a bit similar to the #200 ?

**Comment by ANURAG-PATHAK** [comment]
> hi, is this one a bit similar to the #200 ?

yes both of them are similar 
I think if I am not wrong file name and java public class name should be the same

**Comment by QuakeWang** [comment]
> > hi, is this one a bit similar to the #200 ?
> 
> yes both of them are similar
> I think if I am not wrong file name and java public class name should be the same

You can use this [website](https://pintia.cn/problem-sets/994805342720868352/problems/994805435700199424) to see the specific criteria. The filename in this project is just to find the title name and has nothing to do with the class name.

**Comment by ANURAG-PATHAK** [comment]
> > > hi, is this one a bit similar to the #200 ?
> > 
> > 
> > yes both of them are similar
> > I think if I am not wrong file name and java public class name should be the same
> 
> You can use this [website](https://pintia.cn/problem-sets/994805342720868352/problems/994805435700199424) to see the specific criteria. The filename in this project is just to find the title name and has nothing to do with the class name.

okay, I get it but CodeFactor was giving an error because the public class name and java file name were different. To remove the error we should make the class name and file name the same. this was suggested by CodeFactor
Screenshot 2021-08-07 at 8 38 58 PM
in this image, CodeFactor is suggesting that the class name and file name should be the same.

**Review by QuakeWang — APPROVED** [review]
/approve

**Comment by QuakeWang** [comment]
> > > > hi, is this one a bit similar to the #200 ?
> > > 
> > > 
> > > yes both of them are similar
> > > I think if I am not wrong file name and java public class name should be the same
> > 
> > 
> > You can use this [website](https://pintia.cn/problem-sets/994805342720868352/problems/994805435700199424) to see the specific criteria. The filename in this project is just to find the title name and has nothing to do with the class name.
> 
> okay, I get it but CodeFactor was giving an error because the public class name and java file name were different. To remove the error we should make the class name and file name the same. this was suggested by CodeFactor
> Screenshot 2021-08-07 at 8 38 58 PM
> in this image, CodeFactor is suggesting that the class name and file name should be the same.

This is a wrong I will fix it soon.

**Comment by ANURAG-PATHAK** [comment]
> > > > > hi, is this one a bit similar to the #200 ?
> > > > 
> > > > 
> > > > yes both of them are similar
> > > > I think if I am not wrong file name and java public class name should be the same
> > > 
> > > 
> > > You can use this [website](https://pintia.cn/problem-sets/994805342720868352/problems/994805435700199424) to see the specific criteria. The filename in this project is just to find the title name and has nothing to do with the class name.
> > 
> > 
> > okay, I get it but CodeFactor was giving an error because the public class name and java file name were different. To remove the error we should make the class name and file name the same. this was suggested by CodeFactor
> > Screenshot 2021-08-07 at 8 38 58 PM
> > in this image, CodeFactor is suggesting that the class name and file name should be the same.
> 
> This is a wrong I will fix it soon.

okay, thanks for helping me

**Pull request merged**
